// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Statement = 3,
  LabelDecl = 4,
  VarLabel = 5,
  VarName = 6,
  Number = 7,
  CodeLabel = 8,
  CodeName = 9,
  Instruction = 10,
  Register = 11,
  R1 = 12,
  R0 = 13,
  RC = 14
